[tools]
python = "3.14.4"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.setup]
sources = ["pyproject.toml", "uv.lock"]
run = "uv sync --active"

[tasks.upgrade-deps]
run = "uv sync --upgrade --all-groups"

[tasks.test]
depends = [":setup"]
run = "tox"
