---

name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  prek:
    name: prek
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2.9.1
        with:
          workspaces: |
            wanikani-apprentice
      - uses: j178/prek-action@v2

  files-changed:
    name: Detect which files changed
    runs-on: ubuntu-latest

    outputs:
      python-projects: ${{ steps.projects.outputs.python}}
      wanikani-apprentice: ${{ steps.filter.outputs.wanikani-apprentice }}

    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          list-files: json
          filters: |
            python:
              - 'anki-extract-kanji/**'
              - 'anki-newlines-to-br/**'
              - 'shirabe-jisho-to-anki/**'
              - 'wanikani-burnt-kanji-to-anki/**'
            wanikani-apprentice:
              - 'wanikani-apprentice/**'
      - name: Extract Python project names
        id: projects
        run: |
          set -ex
          echo '${{ steps.filter.outputs.python_files }}' | jq -c 'map(split("/")[0]) | unique' > projects.json
          echo "python=$(cat projects.json)" >> $GITHUB_OUTPUT

  python:
    needs: files-changed
    if: needs.files-changed.outputs.python-projects != '[]'
    name: ${{ matrix.project }} (${{ matrix.toxenv }})
    runs-on: ubuntu-latest
    env:
      TOXENV: ${{ matrix.toxenv }}

    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJSON(needs.files-changed.outputs.python-projects )}}
        toxenv:
          - py,test-coverage
          - mypy

    steps:
      - uses: actions/checkout@v6
      - name: Generate the cache suffix
        id: cache-suffix
        run: |
          echo cache-suffix=${TOXENV//,/-} >> $GITHUB_OUTPUT
      - uses: actions/setup-python@v6
        with:
          python-version-file: ${{ matrix.project }}/pyproject.toml
      - uses: astral-sh/setup-uv@v8.1.0
        with:
          working-directory: ${{ matrix.project }}
          cache-suffix: ${{ steps.cache-suffix.outputs.cache-suffix }}
      - name: tox
        run: uvx tox -c ${{ matrix.project }}

  wanikani-apprentice:
    needs: files-changed
    if: needs.files-changed.outputs.wanikani-apprentice == 'true'
    name: wanikani-apprentice build & test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2.9.1
        with:
          workspaces: |
            wanikani-apprentice
      - name: Run tests
        run: cd wanikani-apprentice && cargo llvm-cov nextest --no-fail-fast --html --color=always
      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: wanikani-apprentice/target/llvm-cov/html

  wanikani-apprentice-deploy:
    needs:
      - wanikani-apprentice
      - prek
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: wanikani-apprentice deploy
    runs-on: ubuntu-latest

    environment:
      name: wanikani-apprentice-prod
      url: https://wk-apprentice.rouge8.com
    concurrency: wanikani-apprentice-prod

    steps:
      - uses: actions/checkout@v6
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd wanikani-apprentice && flyctl deploy --remote-only --env SENTRY_RELEASE=$(git describe --always --abbrev=40)
        env:
          FLY_API_TOKEN: ${{ secrets.WANIKANI_APPRENTICE_FLY_API_TOKEN }}
      - name: Sentry Release
        uses: getsentry/action-release@v3.6.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: rouge8
          SENTRY_PROJECT: wanikani-apprentice
        with:
          environment: prod

  combined-results:
    needs:
      - prek
      - python
      - wanikani-apprentice
    if: always()
    name: Combined result
    runs-on: ubuntu-latest

    steps:
      - name: Check for failures
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo "One or more jobs have failed!" && exit 1
